### ISSUE TITLE
Newer system

### ISSUE THREAD

**Issue by Domochip** [pm2036/palazzetti-firmware#2]
Hello,

Je viens de remarquer, dans une librairie HA, des appels directs à la CBox en UDP mais aussi à partir de la version 2.4.1 des nouveaux appels en TCP ("live data").
Pourrais-tu mettre à jour le contenu de ce repo avec la dernière version?

**Comment by pm2036** [comment]
Salut,
C'est effectivement le fonctionnement de l'appli mobile depuis un moment, c'est géré par /etc/udpsvr.lua il me semble.
Je viens de mettre à jour le repo.

**Comment by Domochip** [comment]
Top! Merci :-D
